.husky/commit-msg, .husky/pre-commit, .npmrc, .prettierignore, commitlint.config.js, package.json, src/layout/Layout.css, yarn.lock
checks if the commit messages meet the conventional commit format
=> chore(Other): Install commitlint and commitizen :hammer:

CONTRIBUTING.md
=> docs: 📚 Add contributing documentation

src/API/Prometheus.constant.ts, src/API/Prometheus.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/Processes.interfaces.ts, src/pages/Processes/components/ChartProcessDataTrafficSeries.tsx, src/pages/Processes/components/Metrics.tsx, src/pages/Processes/services/index.ts
=> feat(Process): :sparkles: Add http request metrics

src/API/Prometheus.constant.ts, src/API/Prometheus.ts, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Processes/Processes.interfaces.ts, src/pages/Processes/components/Metrics.tsx, src/pages/Processes/services/index.ts, src/pages/Processes/views/Process.tsx
=> feat(Process): :sparkles: Add http response charts

src/API/Prometheus.constant.ts, src/API/Prometheus.interfaces.ts, src/API/Prometheus.ts, src/pages/Processes/Processes.interfaces.ts, src/pages/Processes/components/ChartProcessDataTrafficDistribution.tsx, src/pages/Processes/components/Metrics.tsx, src/pages/Processes/services/index.ts
=> Skupper 717 add http response metrics

src/pages/ProcessGroups/views/ProcessGroups.tsx, src/pages/Processes/views/Processes.tsx
=> feat(Process): :sparkles: Add donut chart for error status

src/core/components/Graph/Graph.ts, src/core/utils/bindLinksWithSIteIds.ts, src/core/utils/formatToDecimalPlacesIfCents.ts, src/pages/Processes/components/MetricCard.tsx, src/pages/Processes/components/Metrics.tsx, src/pages/Processes/services/index.ts, src/pages/Topology/components/TopologyPanel.tsx
this is a patch to avoid conflict with api results
Avoid inconsistencies in the topology view in case we receive orphan links from the API
=> fix(Address): :lady_beetle: Skip links without the name property

commitlint.config.js, cypress/e2e/skupper-console/shared/navigation.cy.js, src/API/REST.constant.ts, src/API/REST.ts, src/config.ts, src/core/components/App/index.tsx, src/core/components/AppMenu/AppMenu.tsx, src/pages/Addresses/Addresses.enum.ts, src/pages/ProcessGroups/ProcessGroups.enum.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/Processes.interfaces.ts, src/pages/Processes/components/Metrics.tsx, src/pages/Processes/services/index.ts, src/pages/Sites/Sites.enum.ts, src/pages/Topology/Topology.enum.ts
Changed the menu order items, increased the polling timeout, change data structure for latencies metrics 
=> refactor(Custom): :recycle: Clean code

README.md, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/Graph.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts, src/pages/Topology/services/services.interfaces.ts
=> Remove unused cursor pointer

PULL_REQUEST_TEMPLATE.md
=> chore: :hammer: Add a comprehensive Pull Request template

mocks/data/LINKS.json, mocks/server.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/Graph.ts, src/core/components/Graph/config.ts, src/core/utils/capitalize.spec.ts, src/core/utils/deepCloneArray.spec.ts, src/core/utils/deepCloneArray.ts, src/core/utils/formatBytes.spec.ts, src/core/utils/formatBytes.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts, tsconfig.json
=> perf(Core UI): :zap: Avoid multiple rendering fot the edges

src/core/components/Graph/Graph.ts, src/core/components/Graph/Zoom.ts, src/core/components/Graph/__tests__/Graph.spec.ts, src/core/components/Graph/services.ts
=> perf(Core UI): :zap: Move zoom from graph to submodule

PULL_REQUEST_TEMPLATE.md, README.md, config/webpack.common.js, mocks/server.ts, src/config/config.ts, src/core/utils/bindLinksWithSIteIds.ts, src/index.tsx
now the env variable is COLLECTOR_URL
=> chore: :hammer: Rename env var to get the flow collector url

src/API/Prometheus.interfaces.ts, src/API/Prometheus.ts, src/API/REST.interfaces.ts, src/API/REST.ts, src/API/REST.utils.ts, src/API/axiosMiddleware.ts, src/core/utils/getCurrentAndPastTimestamps.spec.ts, src/core/utils/getCurrentAndPastTimestamps.ts, src/pages/shared/Metrics/services/index.ts
=> refactor: :recycle: Add strict type to the axios responses

src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/services.ts, src/core/utils/bindLinksWithSIteIds.ts, src/pages/Topology/View/Topology.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/services/index.ts
=> refactor(Topology): :recycle: Clean code and topology functions

src/API/REST.interfaces.ts, src/pages/Sites/Sites.constant.ts, src/pages/Sites/__tests__/SiteController.ts, src/pages/Sites/services/index.ts, src/pages/Topology/services/index.ts
=> test(Site): :white_check_mark: Add unit test for bindLinksWithSiteIds

src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts, src/pages/Topology/services/index.ts
=> perf(Topology): :zap: Enable GPU for more than 250 nodes

src/core/components/Graph/GraphMenuControl.tsx
=> fix(Topology): :lady_beetle: Wrong zoom ratio

src/API/REST.interfaces.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts, src/core/components/Graph/customBehaviours.ts, src/pages/Topology/Topology.constant.ts, src/pages/Topology/Topology.interfaces.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts
=> feat(Topology): :sparkles: Mark not exposed processes

src/pages/Processes/Processes.constant.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/components/ProcessDescription.tsx
=> feat(Process): :sparkles: Add exposed flag to the processes table

src/pages/Processes/Processes.constant.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/components/ProcessDescription.tsx, src/pages/Topology/Topology.constant.ts
=> feat(process)🎇 : mark processes exposed

src/API/Prometheus.ts, src/pages/Processes/Processes.constant.ts, src/pages/Processes/Processes.enum.ts, src/pages/shared/Metrics/Filters.tsx, src/pages/shared/Metrics/Metrics.interfaces.ts, src/pages/shared/Metrics/index.tsx
=> fix(Core UI): :lady_beetle: Component metric source filter doesn't show metric with multiple sources

src/pages/Processes/views/ProcessPairs.tsx
=> fix(Process): :lady_beetle: Wrong link to go to the flowpairs details from the process detail view

src/pages/shared/Metrics/index.tsx
=> fix(Process): :lady_beetle: Empty metrics with multiple sources

src/config/testIds.config.ts, src/core/components/Graph/config.ts, src/pages/Topology/services/index.ts
=> feat(Topology): :sparkles: Change protocol labels color based on the protocol

src/API/Prometheus.queries.ts, src/API/Prometheus.ts, src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts, src/core/components/Graph/customBehaviours.ts, src/pages/Topology/Topology.constant.ts, src/pages/Topology/Topology.enum.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts, src/pages/Topology/services/services.enum.ts
=> feat(Topology): :sparkles: Add real time metrics

src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/services.enum.ts
=> feat(Topology): :sparkles: Add remote component to the topology

src/core/components/Graph/GraphReactAdaptor.tsx, src/pages/Topology/components/TopologyProcesses.tsx
=> Add remote process to processgroup

src/core/components/Graph/GraphReactAdaptor.tsx
=> fix(Topology): :lady_beetle: Show link when navigate from flowpairs

src/API/Prometheus.queries.ts, src/core/components/Graph/config.ts, src/pages/Topology/Topology.enum.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts
=> feat(Topology): :sparkles: Add reverse metrics to the processes topology

src/API/REST.enum.ts, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Processes/Processes.constant.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/services/services.enum.ts, src/pages/Processes/views/ProcessPairs.tsx, src/pages/shared/FlowPairs/FlowPair.tsx, src/pages/shared/Metrics/services/index.ts
=> refactor(Core): :recycle: Select terminated connections by api

src/API/Prometheus.queries.ts, src/API/Prometheus.ts, src/config/config.ts, src/pages/shared/Metrics/services/index.ts
=> fix(Core UI): :lady_beetle: Adjust total bytes metric values

src/API/Prometheus.interfaces.ts, src/API/Prometheus.ts, src/core/components/ViewDetailsCell/index.tsx, src/pages/shared/Metrics/services/index.ts
=> Refactor query bytes

src/core/components/ViewDetailsCell/index.tsx, src/pages/Processes/Processes.enum.ts, src/pages/Processes/views/ProcessPairs.tsx
=> fix(General): :lady_beetle: Details button doesn't show links

src/pages/Processes/views/ProcessPairs.tsx, src/pages/Topology/View/Topology.tsx, src/pages/Topology/components/TopologyProcesses.tsx
=> feat(Topology): :sparkles: Update url when change address

src/API/Prometheus.queries.ts, src/API/Prometheus.ts, src/core/components/SkTitle/index.tsx, src/pages/Addresses/Addresses.enum.ts, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Processes/Processes.constant.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/views/ProcessPairs.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/shared/Metrics/LatencyCharts.tsx, src/pages/shared/Metrics/Metrics.enum.ts, src/pages/shared/Metrics/RequestCharts.tsx, src/pages/shared/Metrics/ResponseCharts.tsx, src/pages/shared/Metrics/TrafficCharts.tsx, src/pages/shared/Metrics/index.tsx, src/pages/shared/Metrics/services/index.ts
=> Add byterate  metric to servers

src/API/Prometheus.queries.ts, src/API/Prometheus.ts, src/App.tsx, src/pages/Processes/views/ProcessPairs.tsx
=> fix(General): :lady_beetle: No credential for basic auth

src/pages/Addresses/Addresses.constants.ts, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Processes/Processes.constant.ts
=> refactor(Address): :recycle: Show byte rate rx only for tcp servers

src/pages/Processes/views/ProcessPairs.tsx
=> fix(Process): :lady_beetle: Filter tcp connections only for state

config/webpack.common.js, src/core/components/Wrapper.tsx, src/pages/ProcessGroups/__tests__/ProcessGroup.spec.tsx, src/pages/ProcessGroups/__tests__/ProcessGroups.spec.tsx, src/pages/Sites/__tests__/Site.spec.tsx, src/pages/Sites/__tests__/Sites.spec.tsx
=> chore: :hammer: Add source map

src/pages/Topology/components/TopologyProcesses.tsx
=> fix(Topology): :lady_beetle: Double render when select an address

config/webpack.common.js, src/API/Prometheus.api.ts, src/App.tsx, src/config/Prometheus.config.ts, src/config/config.ts
=> refactor(General): :recycle: Query prometheus from the internal api

config/webpack.common.js, src/core/components/ViewDetailsCell/index.tsx, src/index.tsx
=> style(General): :lipstick: Reduce bundle size selecting css components

src/core/components/EmptyData/EmptyData.enum.ts, src/pages/ProcessGroups/views/ProcessGroups.tsx, src/pages/Processes/Processes.constant.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/views/Process.tsx, src/pages/Processes/views/Processes.tsx, src/pages/Sites/views/Site.tsx, src/pages/shared/FlowPairs/FlowPairs.constant.ts
=> feat(General): :sparkles: Handle remote processes

public/index.html, public/manifest.json, src/pages/shared/Loading/Loading.enum.ts
=> refactor(General): :recycle: Remove skupper references to title and messages

src/core/components/Graph/config.ts
=> refactor(Core UI): :recycle: Decrease topology collosion strength

README.md, config/webpack.common.js, config/webpack.prod.js, public/index.html
=> build(General): :package: Add branding title and favicon

config/webpack.prod.js, src/index.tsx
=> build(General): :package: Name vendors chunks

package.json, src/API/Prometheus.api.ts, src/API/REST.api.ts, src/API/REST.paths.ts, src/App.tsx, src/config/config.ts, src/config/prometheus.ts, src/config/reactQuery.ts, src/core/components/DefaultRoute/index.tsx, src/core/components/NavBar/index.tsx, src/core/components/Wrapper.tsx, src/core/utils/formatChartDate.ts, src/pages/shared/Metrics/Filters.tsx, src/pages/shared/Metrics/services/index.ts, src/routes.tsx, yarn.lock
=> Create a common entry point for the configuration

mocks/data/PROCESS_PAIRS.json, mocks/server.ts, src/config/testIds.config.ts, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/Processes/__tests__/Processes.spec.tsx, src/pages/Processes/components/ProcessDescription.tsx, src/pages/Processes/views/Processes.tsx
=> test(Process): :white_check_mark: Add process unit tests

src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/shared/Metrics/Filters.tsx, src/pages/shared/Metrics/Metrics.interfaces.ts
=>  traffic server sites

mocks/data/ADDRESSES.json, mocks/data/ADDRESS_FLOW_PAIRS.json, mocks/data/ADDRESS_PROCESSES.json, mocks/data/COLLECTORS.json, mocks/data/FLOW_PAIRS.json, mocks/data/HOSTS.json, mocks/data/LINKS.json, mocks/data/PROCESSES.json, mocks/data/PROCESS_GROUPS.json, mocks/data/PROCESS_GROUP_PAIRS.json, mocks/data/PROCESS_PAIRS.json, mocks/data/ROUTERS.json, mocks/data/SITES.json, mocks/server.ts, src/API/REST.interfaces.ts, src/App.tsx, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/services.ts, src/core/components/Wrapper.tsx, src/pages/Sites/Sites.constant.ts, src/pages/Sites/Sites.enum.ts, src/pages/Sites/views/Site.tsx, src/pages/Sites/views/Sites.tsx, src/pages/Topology/Topology.interfaces.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts
=> Add site version

src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts, src/core/components/Graph/services.ts, src/pages/Topology/Topology.interfaces.ts, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/services/index.ts
=> Improve layout topology

mocks/server.ts, src/core/components/Graph/config.ts, src/pages/Topology/services/index.ts
=> refactor(General): :recycle: Enable GPU layout

src/pages/shared/Metrics/services/index.ts
=> perf(Core UI): :zap: Boost metrics API queries

src/pages/shared/Metrics/services/index.ts
=> fix(Core UI): :lady_beetle: Fix test metrics

package.json, src/pages/shared/Metrics/services/index.ts
=> test(Core): :white_check_mark: Disable metrics for tests

src/core/components/Graph/GraphMenuControl.tsx, src/pages/ProcessGroups/views/ProcessGroups.tsx, src/pages/Processes/views/Processes.tsx, src/pages/Sites/Sites.enum.ts, src/pages/Sites/views/Sites.tsx, src/pages/Topology/Topology.enum.ts, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx
=> Add navigation topology table

src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts
=> fix(Topology): :lady_beetle: Fix drag behaviour

mocks/server.ts, src/App.css, src/core/components/SkTable/SkTable.interface.ts, src/core/components/SkTable/index.tsx, src/core/components/SkTitle/index.tsx, src/pages/Addresses/Addresses.constants.ts, src/pages/Addresses/views/Addresses.tsx, src/pages/ProcessGroups/__tests__/ProcessGroup.spec.tsx, src/pages/Processes/Processes.constant.ts, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/shared/Metrics/Filters.tsx
=> refactor(Core UI): :recycle: Redesign tables based on UX design

src/App.css, src/layout/SideBar.tsx
=> style(Core UI): :lipstick: Restoring default navbar and header

src/App.css, src/core/components/ResourceIcon/ResourceIcon.spec.tsx, src/core/components/ResourceIcon/index.tsx, src/pages/Addresses/Addresses.enum.ts, src/pages/Processes/Processes.enum.ts, src/pages/Topology/Topology.enum.ts
=> Fix routing key name

src/App.css
=> style(Core UI): :lipstick: Remove shadow to the badges

src/App.css, src/core/components/Graph/config.ts, src/index.tsx, src/pages/Topology/Topology.enum.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/shared/Metrics/RequestCharts.tsx
=> feat(Topology): :sparkles: Add search bar for filter addresses

src/App.tsx, src/config/reactQuery.ts, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Addresses/views/Addresses.tsx, src/pages/Addresses/views/FlowPairs.tsx, src/pages/ProcessGroups/__tests__/ProcessGroup.spec.tsx, src/pages/ProcessGroups/__tests__/ProcessGroups.spec.tsx, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/ProcessGroups/views/ProcessGroups.tsx, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/Processes/__tests__/Processes.spec.tsx, src/pages/Processes/views/Process.tsx, src/pages/Processes/views/ProcessPairs.tsx, src/pages/Processes/views/Processes.tsx, src/pages/Sites/__tests__/Site.spec.tsx, src/pages/Sites/__tests__/Sites.spec.tsx, src/pages/Sites/views/Site.tsx, src/pages/Sites/views/Sites.tsx, src/pages/Topology/View/Topology.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/shared/Errors/Connection/index.tsx, src/pages/shared/Errors/Console/index.tsx, src/pages/shared/Errors/Http/index.tsx, src/pages/shared/Errors/NotFound/index.tsx, src/pages/shared/Metrics/index.tsx
=> perf(General): :zap: Improve loading api experience

src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Processes/services/services.enum.ts, src/pages/Processes/views/ProcessPairs.tsx
=> fix(Process): :lady_beetle: App crash when a flow pair is selected

src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts, src/pages/Processes/views/ProcessPairs.tsx
=> Fix query undefined

src/pages/Processes/components/ProcessDescription.tsx
=> fix(Process): :lady_beetle: Process pair view sometimes disappear

src/config/reactQuery.ts, src/core/components/Graph/Legend.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/shared/FlowPairs/FlowPairs.constant.ts, src/pages/shared/Metrics/Filters.tsx
=> fix(General): :lady_beetle: Disable staleTime in react query to avoid double calls when suspence is activated

src/API/Prometheus.api.ts, src/API/Prometheus.queries.ts, src/pages/Addresses/services/index.ts, src/pages/Addresses/services/services.enum.ts, src/pages/Addresses/views/Addresses.tsx
=> fix(Services): :lady_beetle: Wrong count of total flowpairs

config/webpack.dev.js, src/App.css, src/index.tsx, src/layout/MainContainer.tsx, src/pages/Topology/View/Topology.tsx
=> refactor(General): :recycle: Adjust padding in the topology header

src/App.tsx
=> fix(Core UI): :lady_beetle: Remove the use of suspense for the Collector API

src/App.css, src/config/config.ts, src/core/components/LinkCell/LinkCell.interfaces.ts, src/core/components/LinkCell/index.tsx, src/core/components/SkTable/SkTable.interface.ts, src/core/components/SkTable/index.tsx
=> feat(Core UI): :sparkles: Add sticky option to the column table

src/core/utils/formatBytes.spec.ts, src/core/utils/formatBytes.ts, src/core/utils/formatChartDate.spec.ts, src/core/utils/formatChartDate.ts, src/core/utils/formatTrace.spec.ts, src/core/utils/formatTrace.ts, src/pages/shared/FlowPairs/FlowPair.tsx
=> test(Core): :white_check_mark: Increase coverage

mocks/data/PROCESS_PAIRS.json, src/API/REST.interfaces.ts, src/core/components/SkTable/index.tsx, src/pages/Processes/Processes.enum.ts, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/Processes/__tests__/ProcessPairs.spec.tsx, src/pages/Processes/components/ProcessDescription.tsx, src/pages/Processes/routes.tsx, src/pages/Processes/views/Process.tsx, src/pages/Processes/views/ProcessPairs.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts
=> refactor(Process): :recycle: Add navigation to the process details

mocks/data/FLOW_PAIRS.json, src/API/REST.interfaces.ts, src/core/components/ViewDetailsCell/ViewDetailCell.interface.ts, src/core/components/ViewDetailsCell/index.tsx, src/pages/Addresses/Addresses.constants.ts, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Processes/Processes.constants.ts, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/Processes/views/ProcessPairs.tsx, src/pages/shared/FlowPair/FlowPair.constants.ts, src/pages/shared/FlowPair/FlowPair.enum.ts, src/pages/shared/FlowPair/FlowPair.tsx, src/pages/shared/FlowPair/FlowPairsTable.tsx, src/pages/shared/FlowPair/__tests__/FlowPair.spec.tsx
=> Rollback flowpairs details

mocks/server.ts, src/core/components/SkCounterCard/SkCounterCart.interfaces.ts, src/core/components/SkCounterCard/index.tsx, src/core/utils/getIdAndNameFromUrlParams.ts, src/pages/Processes/Processes.constants.ts, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/Processes/views/ProcessPairs.tsx, src/pages/shared/FlowPair/FlowPair.constants.ts, src/pages/shared/Metrics/Metrics.interfaces.ts, src/pages/shared/Metrics/ResponseCharts.tsx, src/pages/shared/Metrics/__tests__/Metrics.spec.tsx, src/pages/shared/Metrics/index.tsx
=> test(Site): :white_check_mark: Add req, response and latency charts tests

mocks/data/FLOW_PAIRS.json, src/API/REST.interfaces.ts, src/core/components/ViewDetailsCell/index.tsx, src/pages/Processes/Processes.constants.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/__tests__/Process.spec.tsx, src/pages/Processes/views/ProcessPairs.tsx, src/pages/shared/FlowPair/FlowPair.constants.ts
=> refactor(Process): :recycle: Change process pair view title and improve queries

src/core/components/skSearchFilter/index.tsx, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Addresses/views/Addresses.tsx, src/pages/Processes/views/Processes.tsx
=> Sync search filters with the other one

src/API/REST.interfaces.ts, src/pages/Processes/components/ProcessDescription.tsx
=> fix(Process): :lady_beetle: ImageName undefined crash

src/core/components/skSearchFilter/index.tsx, src/hooks/useDebounce.tsx, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/Addresses/views/Addresses.tsx, src/pages/Processes/views/Processes.tsx
=> refactor(Core UI): :recycle: Create useDebounce

src/core/components/LinkCell/index.tsx, src/pages/Addresses/components/ConnectionsByAddress.tsx, src/pages/Addresses/components/RequestsByAddress.tsx, src/pages/ProcessGroups/ProcessGroups.constants.ts, src/pages/ProcessGroups/__tests__/ProcessGroup.spec.tsx, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/ProcessGroups/views/ProcessGroups.tsx, src/pages/Processes/Processes.constants.ts, src/pages/Processes/components/ProcessDescription.tsx, src/pages/Processes/views/Process.tsx, src/pages/Processes/views/Processes.tsx
=> feat(Component): :sparkles: Add link to processes view

src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/GraphReactAdaptor.tsx, src/core/components/Graph/config.ts, src/core/components/Graph/customItems.ts, src/pages/Topology/services/index.ts
=> feat(Topology): :sparkles: Add badge to the node

src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/GraphReactAdaptor.tsx, src/pages/Topology/__tests__/Topology.spec.tsx, src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx
=> refactor(Topology): :recycle: Move the zoom and fit view logic into topology

src/pages/Topology/Topology.enum.ts
=> refactor(Topology): :recycle: Update display filter labels

src/core/components/SKSanckeyChart/SankeyFilter.tsx, src/pages/Services/Services.enum.ts, src/pages/Services/components/ResourceDistrubutionFlowChart.tsx
=> refactor(Services): :recycle: Add description to the sankey chart

src/pages/Services/Services.enum.ts, src/pages/Services/components/ResourceDistrubutionFlowChart.tsx
=> fix(Services): :lady_beetle: Sankey title chart duplicated

src/pages/Processes/views/Process.tsx, src/pages/Services/components/Overview.tsx, src/pages/shared/Metrics/Metrics.interfaces.ts, src/pages/shared/Metrics/index.tsx
=> refactor(General): :recycle: Remove unused protocols from metric filters

jest.config.ts, mocks/data/COLLECTORS.json, src/pages/ProcessGroups/ProcessGroups.enum.ts, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/Services/Services.enum.ts, src/pages/Services/views/Service.tsx, src/pages/Topology/Topology.enum.ts, src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/shared/Metrics/Filters.tsx, src/pages/shared/Metrics/ResponseCharts.tsx, src/pages/shared/Metrics/__tests__/Filters.spec.tsx, src/pages/shared/Metrics/__tests__/Latency.spec.tsx, src/pages/shared/Metrics/__tests__/Metrics.spec.tsx, src/pages/shared/Metrics/__tests__/Request.spec.tsx, src/pages/shared/Metrics/__tests__/Traffic.spec.tsx, src/pages/shared/Metrics/__tests__/__snapshots__/Latency.spec.tsx.snap, src/pages/shared/Metrics/__tests__/__snapshots__/Request.spec.tsx.snap, src/pages/shared/Metrics/__tests__/__snapshots__/Traffic.spec.tsx.snap, src/pages/shared/Metrics/components/Request.tsx, src/pages/shared/Metrics/index.tsx, src/pages/shared/Metrics/services/index.ts
=> test(Core UI): :white_check_mark: Fix response test

.github/workflows/skupper-console.yml, src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/Topology/components/TopologyProcesses.tsx
=> test(Core UI): :white_check_mark: Increase topology processes coverage

src/API/Prometheus.api.ts, src/API/Prometheus.interfaces.ts, src/App.css, src/core/components/Graph/Graph.constants.ts, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/Processes/components/Overview.tsx, src/pages/Services/components/Overview.tsx, src/pages/Sites/views/Site.tsx, src/pages/shared/Metrics/Metrics.constants.ts, src/pages/shared/Metrics/Metrics.enum.ts, src/pages/shared/Metrics/Metrics.interfaces.ts, src/pages/shared/Metrics/__tests__/Filters.spec.tsx, src/pages/shared/Metrics/__tests__/UpdateMetricsButton.spec.tsx, src/pages/shared/Metrics/__tests__/__snapshots__/Traffic.spec.tsx.snap, src/pages/shared/Metrics/__tests__/index.spec.tsx, src/pages/shared/Metrics/components/Filters.tsx, src/pages/shared/Metrics/components/Latency.tsx, src/pages/shared/Metrics/components/Request.tsx, src/pages/shared/Metrics/components/Traffic.tsx, src/pages/shared/Metrics/components/TrafficCharts.tsx, src/pages/shared/Metrics/components/UpdateMetricsButton.tsx, src/pages/shared/Metrics/index.tsx, src/pages/shared/Metrics/services/index.ts, src/pages/shared/Metrics/services/services.interfaces.ts
=> Refactor metric filter

src/config/colors.ts, src/config/prometheus.ts, src/core/components/Graph/Graph.constants.ts, src/core/utils/formatChartDate.spec.ts, src/core/utils/formatChartDate.ts, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/Processes/components/Overview.tsx, src/pages/Services/components/Overview.tsx, src/pages/Sites/views/Site.tsx, src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/shared/Metrics/Metrics.constants.ts, src/pages/shared/Metrics/Metrics.interfaces.ts, src/pages/shared/Metrics/__tests__/DateTimePicker.spec.tsx, src/pages/shared/Metrics/__tests__/Filters.spec.tsx, src/pages/shared/Metrics/__tests__/UpdateMetricsButton.spec.tsx, src/pages/shared/Metrics/__tests__/index.spec.tsx, src/pages/shared/Metrics/components/DateTimePicker.tsx, src/pages/shared/Metrics/components/Filters.tsx, src/pages/shared/Metrics/components/SelectTimeInterval.tsx, src/pages/shared/Metrics/components/TrafficCharts.tsx, src/pages/shared/Metrics/components/UpdateMetricsButton.tsx, src/pages/shared/Metrics/index.tsx, src/pages/shared/Metrics/services/index.ts
=> feat(Core UI): :sparkles: Improve metric searchability for past events

README.md
Fix the broken link to the docs for enabling skupper console.
=> Fix link to skupper console docs

.github/workflows/commitlint.yml
=> chore(General): :hammer: Add commitlint action

src/API/Prometheus.api.ts, src/API/Prometheus.queries.ts
=> refactor(Metrics): :recycle: Improving query speed to calculate buckets

src/API/Prometheus.queries.ts
=> fix(Metrics): :lady_beetle: Adjust time axis when promtheus reset

package.json, src/API/Prometheus.api.ts, src/API/Prometheus.queries.ts, src/pages/Services/views/Services.tsx, src/pages/shared/Metrics/components/Latency.tsx, src/pages/shared/Metrics/components/Request.tsx, src/pages/shared/Metrics/components/Traffic.tsx, src/pages/shared/Metrics/services/index.ts
=> General cleaning

.github/workflows/release.yml, .github/workflows/skupper-console.yml, mocks/server.ts, package.json, yarn.lock
=> chore(General): :hammer: Update dependencies

src/pages/Processes/views/ProcessPair.tsx
=> fix(Process): :lady_beetle: Avoid glitch when call apis in process pairs

src/pages/Topology/services/index.ts, src/pages/shared/Metrics/__tests__/Response.spec.tsx
=> test(Metrics): :white_check_mark: Request and response unit test empty case

src/layout/Header.tsx
=> fix(Shared): :lady_beetle: Firefox does not show the logo

src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/services/customItems.ts, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/services/index.ts
=> feat(Topology): :sparkles: Change the edge mouseover animation

package.json, src/core/components/Graph/Graph.constants.ts, webpack.dev.js, yarn.lock
=> refactor(Topology): :recycle: Change background topology and combos

src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/ReactAdaptor.tsx, src/pages/Topology/components/DisplayResources.tsx
=> feat(Topology): :sparkles: Deselect process found

src/pages/Topology/services/index.ts
=> feat(Topology): :sparkles: Add loop edge for grouped processes

mocks/data/PROCESS_GROUP_PAIRS.json, mocks/server.ts, src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/MenuControl.tsx, src/core/components/Graph/ReactAdaptor.tsx, src/core/components/Graph/services/index.ts, src/core/components/TransitionPages/Slide.tsx, src/pages/Topology/components/DisplayResources.tsx, src/pages/Topology/components/TopologyModal.tsx, src/pages/Topology/components/TopologyProcesses.tsx
=> feat(Topology): :sparkles: Add slice effect to the topology node details

src/config/config.ts, src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/MenuControl.tsx, src/core/components/Graph/ReactAdaptor.tsx, src/core/components/Graph/services/index.ts, src/core/components/TransitionPages/Fade.tsx, src/core/components/TransitionPages/Slide.tsx, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/Topology/Topology.constants.ts, src/pages/Topology/__tests__/Topology.spec.tsx, src/pages/Topology/components/DisplayServices.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/shared/Loading/index.tsx, src/pages/shared/Metrics/components/Filters.tsx
=> refactor(Topology): :recycle: Improve topology workflow

package.json, src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/MenuControl.tsx, src/core/components/Graph/ReactAdaptor.tsx, src/core/components/Graph/services/customItems.ts, src/core/components/Graph/services/index.ts, src/pages/Sites/Sites.interfaces.ts, src/pages/Sites/components/Details.tsx, src/pages/Sites/services/index.ts, src/pages/Topology/Topology.enum.ts, src/pages/Topology/Topology.interfaces.ts, src/pages/Topology/components/DisplayServices.tsx, src/pages/Topology/components/TopologyModal.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/services/index.ts, yarn.lock
=> Improvements

mocks/data/SITE_PAIRS.json, mocks/server.ts
=> test(General): :white_check_mark: Add site pairs mock data and api

src/config/config.ts, src/core/components/Graph/MenuControl.tsx, src/core/components/Graph/ReactAdaptor.tsx, src/core/components/Graph/services/index.ts, src/pages/Topology/Topology.enum.ts, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx
=> refactor(Topology): :recycle: Add dagree layout to find a node

src/core/components/Graph/ReactAdaptor.tsx
=> feat(Topology): :sparkles: Put a node in front when drag or mouseover

src/core/components/Graph/ReactAdaptor.tsx, src/pages/Topology/components/DisplayResources.tsx, src/pages/Topology/components/DisplayServices.tsx
=> fix(Topology): :lady_beetle: List of services empty creates loops

src/pages/Topology/components/DisplayResources.tsx
=> fix(Site): :lady_beetle: Crash sites view from topology

src/layout/Header.tsx, src/layout/__tests__/Header.spec.tsx
=> test(Shared): :white_check_mark: Increase header unit tests

public/manifest.json, src/layout/Header.tsx, src/layout/__tests__/Header.spec.tsx
=> fix(Shared): :lady_beetle: Logout does not work anymore

src/pages/Processes/components/Details.tsx
=> fix(Process): :lady_beetle: Typo error in service process link

src/core/components/Graph/ReactAdaptor.tsx
=> fix(Topology): :lady_beetle: Site filter topology does not refresh the graph

package.json
=> chore(General): :hammer: Change husky install command to husky

src/App.tsx, src/layout/RouteContainer.tsx
=> fix(Core UI): :lady_beetle: Routing after an app error is not possible

src/core/components/SkUpdateDataButton/index.tsx
Refetch isn't a common term outside of react/apollo clients, changin to 'Refresh' as I think non English speakers will understand better.
=> avoid jargon with 'refetch'

src/config/config.ts, src/pages/ProcessGroups/views/ProcessGroups.tsx, src/pages/Processes/views/Processes.tsx, src/pages/Services/views/Services.tsx, src/pages/Sites/views/Sites.tsx
=> refactor(General): :recycle: Refetch interval for entry views

jest.config.ts, package.json, yarn.lock
=> Fix nivo tests

src/core/components/Graph/Graph.interfaces.ts, src/pages/Topology/components/TopologyProcesses.tsx
=> fix(Process): :lady_beetle: Breadcrumb process pairs source id undefined

cypress/e2e/skupper-console/sites/site.cy.ts, src/hooks/__tests__/useUpdateQueryStringValueWithoutNavigation.spec.tsx, src/hooks/useUpdateQueryStringValueWithoutNavigation.ts, src/pages/ProcessGroups/views/ProcessGroup.tsx, src/pages/Processes/views/Process.tsx, src/pages/Processes/views/ProcessPair.tsx, src/pages/Services/views/Service.tsx, src/pages/Sites/views/Site.tsx, src/pages/Topology/views/Topology.tsx
=> refactor(General): :recycle: Update url query string without rendering all the view

src/core/components/SkUpdateDataButton/__tests__/SkUpdateDataButton.spec.tsx, src/core/components/SkUpdateDataButton/index.tsx
=> test(Core UI): :white_check_mark: Add tests for SkUpdateDataButton

src/API/Prometheus.api.ts, src/API/Prometheus.interfaces.ts, src/API/Prometheus.utils.ts, src/config/reactQuery.ts, src/core/components/SKSanckeyChart/index.tsx, src/core/components/SkChartArea/index.tsx, src/pages/Services/services/index.ts, src/pages/Topology/Topology.interfaces.ts, src/pages/Topology/services/index.ts, src/pages/shared/Metrics/components/TrafficCharts.tsx, src/pages/shared/Metrics/services/index.ts, src/pages/shared/Metrics/services/services.interfaces.ts
=> refactor(General): :recycle: Rewrite prometheus interfaces

mocks/data/LINKS.json, mocks/data/ROUTERS.json, mocks/server.ts, src/API/REST.api.ts, src/API/REST.interfaces.ts, src/API/REST.paths.ts, src/core/components/Graph/Graph.interfaces.ts, src/pages/Sites/Sites.enum.ts, src/pages/Sites/Sites.interfaces.ts, src/pages/Sites/Sites.queries.ts, src/pages/Sites/__tests__/SiteController.spec.ts, src/pages/Sites/components/Details.tsx, src/pages/Sites/services/index.ts, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/services/index.ts
=> Remove router api

src/pages/Topology/services/index.ts
=> fix(Topology): :lady_beetle: Patch processes without sitename but with an existing siteId

src/core/components/EndTimeCell/index.tsx, src/core/components/Graph/Graph.constants.ts, src/core/components/Graph/ReactAdaptor.tsx, src/core/components/Graph/services/customItems.ts, src/pages/Topology/Topology.enum.ts, src/pages/Topology/services/index.ts, src/pages/shared/FlowPairs/FlowPair.constants.ts
=> feat(Topology): :sparkles: Improve metric labels visibility

src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/Topology/__tests__/TopologyToasts.spec.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/components/TopologyToasts.tsx, src/pages/Topology/components/TopologyToolbar.tsx
=> refactor(Topology): :recycle: Abstract topology toolbar

src/core/components/SkChartArea/index.tsx, src/core/components/SkTable/index.tsx, src/pages/Topology/__tests__/TopologyToasts.spec.tsx, src/pages/shared/Metrics/components/TrafficCharts.tsx
=> fix(General): :lady_beetle: Remove typescript compiler errors

src/core/utils/formatTrace.ts, src/pages/shared/FlowPairs/FlowPair.tsx
=> refactor(General): :recycle: Handle undefined trace inputs

package.json, src/pages/Topology/Topology.enum.ts, src/pages/Topology/components/NodeOrEdgeList.tsx, src/pages/Topology/components/TopologyProcesses.tsx
=> Topology drawer

src/API/Prometheus.utils.ts, src/pages/Processes/components/ProcessPairsList.tsx, src/pages/Topology/__tests__/TopologySite.spec.tsx, src/pages/Topology/__tests__/useTopologySiteState.spec.tsx, src/pages/Topology/components/TopologyProcessGroups.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/components/TopologyToolbar.tsx, src/pages/Topology/components/useTopologySiteData.ts, src/pages/Topology/components/useTopologySiteState.ts, src/pages/Topology/services/index.ts, src/pages/Topology/services/topologySiteController.ts, src/pages/Topology/views/Topology.tsx
=> Refactor topology site

src/config/config.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/Graph/ReactAdaptor.tsx, src/pages/Topology/Topology.constants.ts, src/pages/Topology/__tests__/TopologyComponents.spec.tsx, src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/Topology/__tests__/TopologySite.spec.tsx, src/pages/Topology/__tests__/useTopologySiteState.spec.tsx, src/pages/Topology/components/DisplayServices.tsx, src/pages/Topology/components/NodeOrEdgeList.tsx, src/pages/Topology/components/TopologyComponent.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/components/useModalState.ts, src/pages/Topology/components/useServiceState.ts, src/pages/Topology/components/useTopologyComponentData.ts, src/pages/Topology/components/useTopologyProcessData.ts, src/pages/Topology/components/useTopologySiteData.ts, src/pages/Topology/components/useTopologyState.ts, src/pages/Topology/services/index.ts, src/pages/Topology/services/topologyComponentController.ts, src/pages/Topology/services/topologyProcessController.ts, src/pages/Topology/services/topologySiteController.ts, src/pages/Topology/views/Topology.tsx
=> Refactor topology processes

src/pages/Topology/components/TopologyProcesses.tsx
=> fix(Topology): :lady_beetle: Drawer no visible for grouped nodes

src/API/Prometheus.utils.ts, src/pages/Processes/components/Overview.tsx, src/pages/Services/components/Overview.tsx, src/pages/Services/services/index.ts, src/pages/Sites/components/Overview..tsx, src/pages/shared/Metrics/components/Filters.tsx
=> refactor(General): :recycle: Abstract get_prom_site_label functionality

cypress/e2e/skupper-console/sites/site.cy.ts, src/core/components/SkExposureCell/SkExposureCell.interfaces.ts, src/core/components/SkExposureCell/index.tsx, src/pages/Processes/Processes.constants.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/__tests__/ProcessPairs.spec.tsx, src/pages/Processes/components/Details.tsx, src/pages/Services/Services.constants.ts, src/pages/Services/Services.enum.ts, src/pages/Services/__tests__/TcpService.spec.tsx, src/pages/shared/Metrics/Metrics.enum.ts, src/pages/shared/Metrics/components/TcpConnection.tsx
=> Rename live connection

src/core/SkMultiTypeheadWithCheckbox/SkMultiTypeheadWithCheckbox.interfaces.ts, src/core/SkMultiTypeheadWithCheckbox/__tests__/SkMultiTypeheadWithCheckbox.spec.tsx, src/core/SkMultiTypeheadWithCheckbox/__tests__/useData.spec.ts, src/core/SkMultiTypeheadWithCheckbox/index.tsx, src/core/SkMultiTypeheadWithCheckbox/useData.ts, src/core/components/Graph/Graph.interfaces.ts, src/core/components/SkExposureCell/SkExposureCell.interfaces.ts, src/core/components/SkUpdateDataButton/index.tsx, src/pages/Topology/Topology.constants.ts, src/pages/Topology/Topology.enum.ts, src/pages/Topology/Topology.interfaces.ts, src/pages/Topology/__tests__/DisplayOptions.spec.tsx, src/pages/Topology/__tests__/DisplayServices.spec.tsx, src/pages/Topology/__tests__/TopologyProcesses.spec.tsx, src/pages/Topology/__tests__/TopologySite.spec.tsx, src/pages/Topology/__tests__/useTopologyComponentData.spec.ts, src/pages/Topology/__tests__/useTopologyProcessData.spec.ts, src/pages/Topology/__tests__/useTopologySiteData.spec.ts, src/pages/Topology/components/DisplayOptions.tsx, src/pages/Topology/components/DisplayResources.tsx, src/pages/Topology/components/DisplayServices.tsx, src/pages/Topology/components/TopologyToolbar.tsx, src/pages/Topology/components/useTopologyComponentData.ts, src/pages/Topology/components/useTopologyProcessData.ts, src/pages/Topology/components/useTopologySiteData.ts, src/pages/Topology/views/Topology.tsx
=> feat(Topology): :sparkles: Add multiTypeheadWithCheckbox

src/App.tsx, src/core/components/NavigationViewLink/index.tsx, src/core/components/SkUpdateDataButton/__tests__/SkUpdateDataButton.spec.tsx, src/core/components/SkUpdateDataButton/index.tsx, src/layout/MainContainer.tsx, src/pages/Topology/components/TopologyComponent.tsx, src/pages/Topology/components/TopologyProcesses.tsx, src/pages/Topology/components/TopologySite.tsx, src/pages/Topology/components/TopologyToolbar.tsx, src/pages/Topology/views/Topology.tsx
=> refactor(General): :recycle: Adapt the referesh button to the new design

package.json, src/core/components/SkTable/index.tsx, src/pages/Services/components/ResourceDistrubutionFlowChart.tsx, src/pages/Services/services/index.ts, src/pages/shared/Metrics/components/Filters.tsx, tsconfig.json, yarn.lock
=> fix(General): :lady_beetle: Remove typescript errors

src/core/components/SkUpdateDataButton/index.tsx
=> fix(Core UI): :lady_beetle: Refresh button re-rerender to much time during loading

src/pages/Topology/components/useTopologyProcessData.ts
=> fix(Topology): :lady_beetle: Wrong neighbours aggregation for processes aggregated

src/App.css, src/layout/Header.tsx, src/layout/__tests__/Header.spec.tsx
=> feat(Core UI): :sparkles: Change dark mode switch layout

src/pages/Topology/components/EdgeDetails.tsx, src/pages/Topology/components/NodeDetails.tsx
=> refactor(Topology): :recycle: Add metrics to the edge topology details

mocks/server.ts, package.json, src/API/Prometheus.queries.ts, src/pages/Services/components/ExposedServers.tsx, yarn.lock
=> refactor(Services): :recycle: Adjust service byterate details

src/pages/Processes/components/ProcessPairsList.tsx, src/pages/Sites/components/Overview..tsx, src/pages/Topology/components/NodeDetails.tsx, src/pages/shared/Metrics/index.tsx
=> Fix topology metric detail

__tests__/pages/Processes/ProcessPairs.spec.tsx, src/core/components/SkFlowPairsTable/FlowPair.constants.ts, src/pages/ProcessGroups/Components.constants.ts, src/pages/Processes/Processes.constants.ts, src/pages/Processes/components/Details.tsx, src/pages/Processes/components/FlowPairsList.tsx, src/pages/Services/Services.constants.ts, src/pages/Sites/Sites.constants.ts, src/pages/Sites/hooks/useSiteData.ts, src/pages/Sites/hooks/useSiteProcessListData.ts, src/pages/Sites/views/Site.tsx, src/pages/Topology/services/topologySiteController.ts
=> Minor fix v2

src/core/components/SkLinkCell/index.tsx, src/pages/Services/hooks/useServicesData.ts, src/types/REST.interfaces.ts
=> refactor(Services): :recycle: Add isBound flag

__tests__/core/SkLinkCell.spec.tsx, __tests__/pages/Services/Service.spec.tsx, src/core/components/SkTable/SkTable.utils.ts, src/core/components/SkTable/index.tsx, src/pages/ProcessGroups/components/ProcessList.tsx, src/pages/Processes/Processes.constants.ts, src/pages/Processes/Processes.enum.ts, src/pages/Processes/components/FlowPairsList.tsx, src/pages/Services/Services.constants.ts, src/pages/Services/Services.enum.ts, src/pages/Services/components/HttpRequests.tsx, src/pages/Services/components/NavigationMenu.tsx, src/pages/Services/components/TcpConnections.tsx, src/pages/Sites/components/ProcessList.tsx
=> refactor(General): :recycle: Hide table columns programmatically

src/pages/shared/Metrics/services/index.ts
=> Fix services metrics

mocks/data/LINKS.json, src/core/components/SkGraph/services/index.ts
=> refactor(Topology): :recycle: Improve sensibility of visual distribution

src/API/REST.api.ts
=> fix(Site): :lady_beetle: Duplicate links cause errors in the topology

src/pages/shared/Metrics/services/index.ts
=> fix(Metrics): :lady_beetle: Fix negative percentage of http responses

package.json, src/core/components/SkGraph/services/index.ts, src/types/Graph.interfaces.ts, webpack.prod.js, yarn.lock
=> Fix protocol label

package.json, src/core/components/SKSanckeyChart/SkSankey.constants.ts, src/pages/Services/components/HttpRequests.tsx, src/pages/Services/components/PairsSankeyChart.tsx, src/pages/Services/components/ProcessServerList.tsx, src/pages/Services/components/TcpConnections.tsx, src/pages/Services/components/TcpTerminatedConnections.tsx, src/pages/Services/views/Service.tsx, yarn.lock
=> Move sankey

src/pages/ProcessGroups/components/Overview..tsx, src/pages/Processes/components/Overview.tsx, src/pages/Services/components/Overview.tsx, src/pages/Sites/components/Overview..tsx, src/pages/shared/Metrics/index.tsx
=> Fix show http

.github/workflows/dev-build.yml
=> refactor(General): :recycle: Use artifacts

.github/workflows/artifact-dev.yml, webpack.common.js
=> chore(General): :hammer: Add artifact generator

.github/workflows/artifact-dev.yml
=> Optimize action

.github/workflows/artifact-dev.yml
=> fix(General): :lady_beetle: Fix upload path

.github/workflows/release.yml, .github/workflows/skupper-console.yml, package.json, yarn.lock
=> chore(General): :hammer: Update build action

.github/workflows/release.yml, .github/workflows/skupper-console.yml, webpack.prod.js
=> chore(General): :hammer: Add webapack cache

.github/workflows/release.yml, package.json, yarn.lock
=> perf(General): :zap: Cypress can be ignored

src/pages/Topology/components/TopologyProcesses.tsx
=> Improve topoloogy service filtering

src/core/components/SkBiFlowList/BiFlowList.constants.ts, src/core/components/SkGraph/layout.ts, src/layout/MainContainer.tsx, src/pages/ProcessGroups/Components.enum.ts, src/pages/Processes/Processes.enum.ts, src/pages/Services/Services.enum.ts, src/pages/Services/components/ListenerAndConnectorList.tsx, src/pages/Topology/services/index.ts
=> Polite services

src/API/REST.api.ts, src/pages/Services/hooks/useListenersAndConnectorsData.ts, src/pages/Services/hooks/useServicesData.ts, src/pages/Services/services/index.ts, src/types/REST.interfaces.ts
=> Update console service flag

src/core/components/SkGraph/index.tsx
=> fix: :lady_beetle: ExcludeBehaviors undefined crash the graph

README.md
=> docs: :books: Update network observer references

src/core/components/SkGraph/components/CustomElements.ts
=> feat(Topology): :sparkles: Add num process badge to remote node

README.md, __tests__/pages/Metrics/__snapshots__/Metrics.spec.tsx.snap
=> Update doc v1

yarn.lock
=> chore: :hammer: Update lock file

package.json, src/core/components/SkGraph/behaviours.ts, src/core/components/SkGraph/index.tsx
=> Fix zoom canvas

jest.config.ts, package.json, vite.config.ts, yarn.lock
=> Remove no necessary opt jest

README.md, mocks/server.ts, package.json, src/config/api.ts, src/index.tsx, vite.config.ts
=> refactor: :recycle: Rename env variables

README.md
=> docs: :books: Fix github action name to display the badge

__tests__/Metric.spec.tsx, __tests__/MetricServices.spec.ts, package.json, src/pages/Processes/components/BiFlowList.tsx, vite.config.ts, yarn.lock
=> test: :white_check_mark: Remove warnings

.github/workflows/build.yml, .github/workflows/commitlint.yml, .github/workflows/release.yml
=> ci: :ferris_wheel: Remove v2 branch from actions

package.json, vite.config.ts, yarn.lock
=> fix: :lady_beetle: React swc crash with pp64le architectures

src/config/api.ts
=> refactor(API): :recycle: Change base version path

src/config/styles.ts, src/core/components/ResourceIcon/index.tsx, src/pages/Services/Services.constants.ts
=> fix(Services): :lady_beetle: Process data link wrong icon

cypress.config.ts
=> test: :white_check_mark: Use env variable to set url domain in cypress

.github/workflows/build.yml, cypress/local/sites/navigation.cy.ts, package.json
=> ci: :ferris_wheel: Add cross browser cypress

package.json, yarn.lock
=> fix: :lady_beetle: Dependecy not from the npm registry

src/API/Prometheus.utils.ts, src/core/components/SkCharts/SkChartArea/SkChartArea.constants.ts, src/core/components/SkCharts/SkChartArea/SkChartArea.utils.ts
=> refactor(Metrics): :recycle: Use 1 decimal for metric values

__tests__/formatLatency.spec.ts
=> test(Core utils): :white_check_mark: Add latency tests

__tests__/ErrorConsole.spec.tsx
=> test(Shared): :white_check_mark: Add error console tests

src/config/labels.ts
=> fix: :lady_beetle: Wrong process description

index.html, src/App.css, src/core/components/SkTable/SkCustomCells/SkViewDetailsCell/index.tsx, src/index.tsx
=> refactor: :recycle: Add app css

README.md, src/config/api.ts, src/config/labels.ts, src/config/navigation.ts, src/config/prometheus.ts, src/config/styles.ts, src/config/testIds.ts
=> docs: :books: Add project structure ref.
